name: handball_ergebnisse
description: Own implementation of 7Meter App

publish_to: 'none'

version: 1.1.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  json_serializable: ^5.0.2
  build_runner: ^2.1.2
  http: ^0.13.3
  skeleton_loader: ^2.0.0+4
  shared_preferences: ^2.0.8
  timelines: ^0.1.0
  flutter_pdfview: ^1.2.1
  path_provider: ^2.0.5
  share: ^2.0.4
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  string_similarity: ^2.0.0
  maps_launcher: ^2.0.1
  device_info_plus: ^3.2.3
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/handball.jpg
